<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.0.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Apply Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U990' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U968' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Industry of Interest',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Industry of Interest\' is required.'
			)
		),
		'custom_U972' => array(
			'order' => 5,
			'type' => 'string',
			'label' => ' Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \' Address\' is required.'
			)
		),
		'custom_U962' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City\' is required.'
			)
		),
		'custom_U980' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Province',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Province\' is required.'
			)
		),
		'custom_U976' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Postal Code',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Postal Code\' is required.'
			)
		),
		'custom_U954' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Age',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Age\' is required.'
			)
		),
		'custom_U958' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Marital Status',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Marital Status\' is required.'
			)
		),
		'custom_U1083' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Cell Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Cell Phone\' is required.'
			)
		),
		'custom_U1107' => array(
			'order' => 1,
			'type' => 'radiogroup',
			'label' => 'Account Type',
			'required' => true,
			'optionItems' => array(
				'Employee',
				'Student'
			),
			'errors' => array(
				'required' => 'Field \'Account Type\' is required.',
				'format' => 'Field \'Account Type\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
